# Generated by Django 5.0 on 2023-12-06 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="esclavizadordocumentoconexion",
            name="persona_altura",
        ),
        migrations.RemoveField(
            model_name="esclavizadordocumentoconexion",
            name="persona_edad",
        ),
        migrations.RemoveField(
            model_name="esclavizadordocumentoconexion",
            name="personas_esclavizadas",
        ),
        migrations.AddField(
            model_name="esclavizadordocumentoconexion",
            name="esclavizador",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esclavizador_relaciones",
                to="person.esclavizador",
            ),
            preserve_default=False,
        ),
    ]
