# Generated by Django 5.0 on 2023-12-06 00:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Name of Document Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Nombre de Archivo"
                    ),
                ),
                (
                    "lugar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archivos",
                        to="geo.lugar",
                        verbose_name="Lugares de Archivos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fondo", models.CharField(max_length=20)),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fondos",
                        to="document.archivo",
                        verbose_name="Archivo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubFondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subfondo", models.CharField(max_length=20)),
                (
                    "fondo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfondos",
                        to="document.fondo",
                        verbose_name="Fondos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Volumen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volumen", models.CharField(max_length=20)),
                (
                    "subfondo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfondos",
                        to="document.subfondo",
                        verbose_name="SubFondo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "ano",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2000),
                        ],
                    ),
                ),
                (
                    "fuente_folio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("resumen", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "evento_valor",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "evento_forma_de_pago",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "evento_total",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "asunto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="document.asunto",
                    ),
                ),
                (
                    "volumen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.volumen",
                    ),
                ),
            ],
        ),
    ]
